#!/bin/bash

# This aims to set up for development of Zanata's website by cloning the
# website repository into ~/src/zanata.github.io and installing jekyll
# so that the website can be served locally with `jekyll serve`.

# TODO run the script to get the code
echo "Please run fedora-setup-zanata-website-get-code"
# TODO run the script to set up jekyll
echo "Please run fedora-setup-zanata-website-prepare-jekyll"

