#!/bin/bash

# This aims to set up for development of Zanata's website by cloning the
# website repository into ~/src/zanata.github.io and installing jekyll
# so that the website can be served locally with `jekyll serve`.

# Clone the website repository
git clone git@github.com:zanata/zanata.github.io.git ~/src/zanata/zanata.github.io

# TODO install jekyll, see instructions on the zanata.github.io README for
#      guidance.

