#!/bin/bash

# Modify settings etc. to make a plain Fedora install behave the way I want it
# to.


# Get my SSH keys installed
# This time I just copied them manually on a USB stick.
# Note that the ~/.ssh folder also has known_hosts, which I can copy across
# to prevent being asked about adding servers to known hosts. This may be
# handy for allowing scripts that use SSH to run without needing user input.


# Add "Open in terminal" to nautilus right-click menu
yum install -y nautilus-open-terminal
killall nautilus

# Show the date in the clock at the top of the screen
gsettings set org.gnome.desktop.interface clock-show-date true

# I believe this is necessary to allow accessing the iPhone through USB
# FIXME seems that usbmuxd is getting permission here, not sure if this is
#       what I want in general.
grep usbmuxd /var/log/audit/audit.log | audit2allow -M mypol
semodule -i mypol.pp

# The battery icon does not display without this
sudo yum install -y acpi

# Make workspaces apply to all monitors, not just primary
gsettings set org.gnome.shell.overrides workspaces-only-on-primary false
